In [174]:
import pandas as pd
import numpy as np

In [175]:
df_antigo = pd.read_csv('narahoteisbases/funcionarios.csv', sep=';')
df_novo = pd.read_csv('narahoteisbases_nova/funcionarios_novos.csv', sep=';')

In [176]:
df = pd.concat(
    [df_antigo, df_novo],
    ignore_index=True
)
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
...,...,...,...,...,...,...,...
139,140,13,Camila Ferreira,Segurança,Governança,"""4.710,88""",2024-09-27
140,141,13,Diego Ramos,analista financeiro,A&B,"""8.932,76""",2024-03-21
141,142,13,Juliana Prado,Chef de Cozinha,Operações,NaN,2024-03-12
142,143,13,Leonardo Vaz,Manobrista,operações,"""2.782,48""",2024-08-26
143,144,13,Renata Castro,Segurança,Financeiro,"""8.289,01""",2024-06-15

In [177]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  144 non-null    int64
 1   id_unidade      144 non-null    int64
 2   nome            144 non-null    str
 3   cargo           144 non-null    str
 4   departamento    144 non-null    str
 5   salario         137 non-null    str
 6   data_admissao   144 non-null    str
dtypes: int64(2), str(5)
memory usage: 8.0 KB

### Texto:

In [178]:
mascara = df['nome'].str.startswith(' ') | df['nome'].str.endswith(' ')
df.loc[mascara, 'nome'].tolist()

[]

#### Cargo:

In [179]:
df['cargo'] = df['cargo'].str.strip().str.title()

In [180]:
df['cargo'].value_counts().reset_index()

                  cargo  count
0            Manutenção     24
1             Segurança     22
2             Camareira     21
3   Auxiliar De Limpeza     18
4   Analista Financeiro     15
5         Recepcionista     15
6            Cozinheiro     15
7               Gerente      9
8             Sommelier      2
9             Concierge      1
10      Chef De Cozinha      1
11           Manobrista      1

#### Departamento:

In [181]:
df['departamento'] = df['departamento'].str.strip().str.title()

In [182]:
df['departamento'].value_counts().reset_index()

           departamento  count
0            Governança     33
1            Manutenção     24
2             Segurança     20
3            Financeiro     15
4              Recepção     15
5   Alimentos E Bebidas     13
6                  Gov.      8
7         Administração      8
8                   A&B      5
9             Operações      2
10               Admin.      1

In [183]:
mapa = {
'Gov.':'Governança',
'Admin.':'Administração',
'A&B':'Alimentos e Bebidas',
'Alimentos E Bebidas':'Alimentos e Bebidas',
}
df['departamento'] = df['departamento'].map(mapa).fillna(df['departamento'])

In [184]:
df['departamento'].value_counts().reset_index()

          departamento  count
0           Governança     41
1           Manutenção     24
2            Segurança     20
3  Alimentos e Bebidas     18
4           Financeiro     15
5             Recepção     15
6        Administração      9
7            Operações      2

### Salario e data:

In [185]:
df['salario'] = df['salario'].astype(str).str.replace('.','',regex=False).str.replace('"','',regex=False).str.replace("'","",regex=False).str.replace('-','',regex=False).str.replace(',','.',regex=False).str.strip().astype(float)

In [186]:
df['data_admissao'] = pd.to_datetime(
    df['data_admissao'],
    yearfirst=True
)
df.isnull().sum().reset_index()

            index  0
0  id_funcionario  0
1      id_unidade  0
2            nome  0
3           cargo  0
4    departamento  0
5         salario  7
6   data_admissao  0

### Nulos e duplicados:

#### Nulos:

In [187]:
df.isnull().sum().reset_index()

            index  0
0  id_funcionario  0
1      id_unidade  0
2            nome  0
3           cargo  0
4    departamento  0
5         salario  7
6   data_admissao  0

In [188]:
df[df.isnull().any(axis=1)]

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
8,9,1,Bruno Costa,Auxiliar De Limpeza,Governança,NaN,2021-11-02
13,14,1,Yuri Castro,Analista Financeiro,Financeiro,NaN,2022-12-31
36,37,4,Larissa Sousa,Cozinheiro,Alimentos e Bebidas,NaN,2019-09-29
42,43,4,Wilson Duarte,Analista Financeiro,Financeiro,NaN,2022-01-07
91,92,9,Wilson Duarte,Gerente,Administração,NaN,2024-02-29
103,104,10,Vanessa Cavalcanti,Cozinheiro,Alimentos e Bebidas,NaN,2024-05-27
141,142,13,Juliana Prado,Chef De Cozinha,Operações,NaN,2024-03-12

In [189]:
df['nome'] = df['nome'].str.title()

In [190]:
df[df.duplicated(subset=['nome','departamento', 'cargo', 'id_unidade'], keep=False)].sort_values(by='nome')

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
60,61,6,Kleber Pires,Camareira,Governança,1531.0,2022-05-26
62,63,6,Kleber Pires,Camareira,Governança,1616.0,2018-11-03

In [191]:
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.00,2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,1746.00,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.00,2022-03-01
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.00,2019-06-10
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.00,2018-10-16
...,...,...,...,...,...,...,...
139,140,13,Camila Ferreira,Segurança,Governança,4710.88,2024-09-27
140,141,13,Diego Ramos,Analista Financeiro,Alimentos e Bebidas,8932.76,2024-03-21
141,142,13,Juliana Prado,Chef De Cozinha,Operações,NaN,2024-03-12
142,143,13,Leonardo Vaz,Manobrista,Operações,2782.48,2024-08-26
143,144,13,Renata Castro,Segurança,Financeiro,8289.01,2024-06-15

In [192]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  144 non-null    int64
 1   id_unidade      144 non-null    int64
 2   nome            144 non-null    str
 3   cargo           144 non-null    str
 4   departamento    144 non-null    str
 5   salario         137 non-null    float64
 6   data_admissao   144 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 8.0 KB

### Adições e alterações:

In [193]:
ids_funcionarios = {
    9: 1870.0, # Bruno Costa
    14: 5480.0, # Yuri Castro
    37: 2950.0, # Larissa Souza
    43: 5600.0, # Wilson Duarte
    92: 8600.0, # Wilson Duarte
    104: 2890.0, # Vanessa Cavalcante
    # Negativo foi ajustado na transformação do float
    26: 2150.0, # Gabriel lima
    142: 7850.0, # Juliana Prado
}

for id_func, salario  in ids_funcionarios.items():
    df.loc[df['id_funcionario'] == id_func, 'salario'] = id_func