In [3]:
import pandas as pd
import numpy as np

In [4]:
df_antigo = pd.read_csv('narahoteisbases/clientes.csv', sep=';')
df_novo = pd.read_csv('narahoteisbases_nova/clientes_novos.csv', sep=';')

In [5]:
df = pd.concat(
    [df_antigo, df_novo],
    ignore_index=True
)
df

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física
...,...,...,...,...,...,...
316,316,Priscila Guimarães,Lisboa,EX,NaN,PF
317,317,Rodrigo Vasques,Rio de Janeiro,RJ,36-45,PF
318,318,Sabrina Leitão,Brasília,DF,46-55,PF
319,319,Thiago Bicalho,Belo Horizonte,MG,46-55,Pessoa Jurídica
320,320,Vivian Lacerda,Buenos Aires,EX,56-65,Pessoa Jurídica

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_cliente     321 non-null    int64
 1   nome           321 non-null    str
 2   cidade_origem  321 non-null    str
 3   estado_origem  321 non-null    str
 4   faixa_etaria   290 non-null    str
 5   tipo_cliente   321 non-null    str
dtypes: int64(1), str(5)
memory usage: 15.2 KB

### Tratamento cidade origem

In [7]:
df['cidade_origem'] = df['cidade_origem'].str.strip().str.title().str.replace('De', 'de', regex=False) # Caso especial apenas para que fique Rio de Janeiro invés de Rio De Janeiro
df.head(10)

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física
5,6,Ulisses Brito,Brasília,RS,56-65,Pessoa Física
6,7,Kleber Pires,São Paulo,ES,65+,pessoa fisica
7,8,Olivia Freitas,Brasília,PA,18-25,Corporativo
8,9,Wesley Araujo,Belo Horizonte,ES,NaN,Corporativo
9,10,Ivan Azevedo,Curitiba,PE,26-35,pf

In [8]:
df['cidade_origem'].value_counts().reset_index()

     cidade_origem  count
0        Fortaleza     46
1        São Paulo     42
2           Recife     41
3         Curitiba     40
4         Brasília     36
5   Belo Horizonte     36
6         Salvador     36
7   Rio de Janeiro     34
8           Lisboa      2
9     Buenos Aires      2
10    Porto Alegre      2
11       Nova York      2
12         Niterói      1
13           Miami      1

### Tratamento tipo de cliente

In [9]:
df['tipo_cliente'] = df['tipo_cliente'].str.strip().str.title()
map_cliente = {
    'Pf': 'Pessoa Física',
    'Pessoa Fisica': 'Pessoa Física',
    'Pj': 'Corporativo'
}
df['tipo_cliente'] = df['tipo_cliente'].map(map_cliente).fillna(df['tipo_cliente'])

In [10]:
df['tipo_cliente'].value_counts().reset_index()

      tipo_cliente  count
0      Corporativo    165
1    Pessoa Física    150
2  Pessoa Jurídica      6

### Tratamento de nome

In [11]:
df['nome'] = df['nome'].str.strip().str.title()

In [12]:
mascara = df['nome'].str.startswith(' ') | df['nome'].str.endswith(' ')
df.loc[mascara, 'nome'].tolist()

[]

### Verificando faixa etária:

In [13]:
df['faixa_etaria'].value_counts().reset_index().sort_values(by='faixa_etaria')

  faixa_etaria  count
5        18-25     43
4        26-35     44
3        36-45     46
1        46-55     50
2        56-65     47
0          65+     60

### Nulos e POSSÍVEIS duplicatas

In [14]:
df.isnull().sum().reset_index()

           index   0
0     id_cliente   0
1           nome   0
2  cidade_origem   0
3  estado_origem   0
4   faixa_etaria  31
5   tipo_cliente   0

In [15]:
df[df.duplicated(subset=['nome', 'cidade_origem', 'faixa_etaria'], keep=False)].sort_values(by='nome')

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
30,31,Abel Correia,Rio de Janeiro,RS,46-55,Pessoa Física
57,58,Abel Correia,Rio de Janeiro,CE,46-55,Pessoa Física
194,195,Carlos Neto,Fortaleza,DF,36-45,Corporativo
66,67,Carlos Neto,Salvador,BA,26-35,Corporativo
85,86,Carlos Neto,Fortaleza,ES,46-55,Corporativo
184,185,Carlos Neto,Fortaleza,SP,36-45,Pessoa Física
152,153,Carlos Neto,Salvador,GO,26-35,Pessoa Física
253,254,Carlos Neto,Fortaleza,PR,46-55,Pessoa Física
37,38,Daniela Ramos,São Paulo,PR,18-25,Pessoa Física
153,154,Daniela Ramos,São Paulo,CE,18-25,Pessoa Física
144,145,Fernanda Cruz,Curitiba,DF,46-55,Corporativo
241,242,Fernanda Cruz,Curitiba,BA,46-55,Pessoa Física
247,248,Gustavo Vieira,Fortaleza,Rio de Janeiro,18-25,Pessoa Física
110,111,Gustavo Vieira,Fortaleza,PA,18-25,Corporativo
255,256,Helena Borges,Salvador,SC,36-45,Pessoa Física
136,137,Helena Borges,Salvador,GO,36-45,Pessoa Física
112,113,Henrique Rocha,Recife,RJ,NaN,Pessoa Física
14,15,Henrique Rocha,Recife,MG,NaN,Pessoa Física
202,203,João Pereira,Rio de Janeiro,GO,65+,Corporativo
252,253,João Pereira,Rio de Janeiro,PA,65+,Pessoa Física
162,163,Olivia Freitas,Curitiba,PA,18-25,Corporativo
24,25,Olivia Freitas,Curitiba,SP,18-25,Corporativo
93,94,Rafael Cardoso,Fortaleza,RJ,18-25,Corporativo
43,44,Rafael Cardoso,Fortaleza,RJ,18-25,Corporativo
224,225,Roberta Leite,Salvador,PA,36-45,Corporativo
16,17,Roberta Leite,Salvador,GO,36-45,Corporativo
209,210,Ximena Godoi,Fortaleza,CE,NaN,Corporativo
228,229,Ximena Godoi,Fortaleza,SC,NaN,Pessoa Física

In [16]:
df[df.isnull() 
.any(axis=1)]

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
8,9,Wesley Araujo,Belo Horizonte,ES,NaN,Corporativo
14,15,Henrique Rocha,Recife,MG,NaN,Pessoa Física
15,16,Marcos Andrade,São Paulo,RS,NaN,Corporativo
19,20,Thiago Matos,Fortaleza,ES,NaN,Pessoa Física
28,29,Isabela Martins,São Paulo,SC,NaN,Corporativo
38,39,Ivan Azevedo,Curitiba,ES,NaN,Corporativo
42,43,Roberta Leite,Recife,CE,NaN,Corporativo
52,53,Bruno Costa,Recife,SP,NaN,Pessoa Física
68,69,Isabela Martins,Recife,MG,NaN,Corporativo
92,93,Gabriela Lima,Belo Horizonte,PA,NaN,Corporativo
95,96,Quezia Nunes,Rio de Janeiro,PA,NaN,Pessoa Física
99,100,Otavio Reis,Rio de Janeiro,ES,NaN,Pessoa Física
107,108,Rafael Cardoso,Brasília,MG,NaN,Corporativo
112,113,Henrique Rocha,Recife,RJ,NaN,Pessoa Física
121,122,Ana Silva,Salvador,PE,NaN,Corporativo
123,124,Ursula Pinto,Salvador,CE,NaN,Corporativo
142,143,Henrique Rocha,Belo Horizonte,MG,NaN,Pessoa Física
165,166,Kleber Pires,Curitiba,CE,NaN,Pessoa Física
172,173,Elena Santos,Brasília,SC,NaN,Pessoa Física
174,175,Ursula Pinto,São Paulo,MG,NaN,Corporativo
181,182,Thiago Matos,São Paulo,RS,NaN,Pessoa Física
188,189,Thiago Matos,Recife,CE,NaN,Corporativo
199,200,Gustavo Vieira,São Paulo,PR,NaN,Corporativo
201,202,Wilson Duarte,Curitiba,PE,NaN,Corporativo
204,205,Otavio Reis,Brasília,GO,NaN,Pessoa Física
209,210,Ximena Godoi,Fortaleza,CE,NaN,Corporativo
228,229,Ximena Godoi,Fortaleza,SC,NaN,Pessoa Física
269,270,Lucas Souza,São Paulo,DF,NaN,Corporativo
295,296,Carlos Neto,Recife,PA,NaN,Pessoa Física
304,304,Débora Vasconcelos,Miami,EX,NaN,Pessoa Física
316,316,Priscila Guimarães,Lisboa,EX,NaN,Pessoa Física