In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv("narahoteisbases/funcionarios.csv", sep=';')
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,"""2.221,00""",2020-08-16
130,131,12,Abel Correia,Gerente,Administração,"""8.404,00""",2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,"""2.700,00""",2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,"""2.442,00""",2023-02-17

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    str
 6   data_admissao   134 non-null    str
dtypes: int64(2), str(5)
memory usage: 7.5 KB

### Texto:

In [55]:
mascara = df['nome'].str.startswith(' ') | df['nome'].str.endswith(' ')
df.loc[mascara, 'nome'].tolist()

[]

#### Cargo:

In [56]:
df['cargo'] = df['cargo'].str.strip().str.title()

In [57]:
df['cargo'].value_counts().reset_index()

                 cargo  count
0           Manutenção     24
1            Camareira     21
2            Segurança     20
3  Auxiliar De Limpeza     17
4        Recepcionista     15
5           Cozinheiro     15
6  Analista Financeiro     13
7              Gerente      9

#### Departamento:

In [58]:
df['departamento'].value_counts().reset_index()

          departamento  count
0           Governança     30
1           Manutenção     24
2            Segurança     20
3             Recepção     15
4           Financeiro     13
5  Alimentos e Bebidas     13
6                 Gov.      8
7        Administração      8
8                  A&B      2
9               Admin.      1

In [59]:
mapa = {
'Gov.':'Governança',
'Admin.':'Administração',
'A&B':'Alimentos e Bebidas',
}
df['departamento'] = df['departamento'].map(mapa).fillna(df['departamento'])

In [60]:
df['departamento'].value_counts().reset_index()

          departamento  count
0           Governança     38
1           Manutenção     24
2            Segurança     20
3             Recepção     15
4  Alimentos e Bebidas     15
5           Financeiro     13
6        Administração      9

### Salario e data:

In [61]:
df['salario'] = df['salario'].astype(str).str.replace('.','',regex=False).str.replace('"','',regex=False).str.replace("'","",regex=False).str.replace('-','',regex=False).str.replace(',','.',regex=False).str.strip().astype(float)

In [62]:
df['data_admissao'] = pd.to_datetime(
    df['data_admissao'],
    yearfirst=True
)
df.isnull().sum().reset_index()

            index  0
0  id_funcionario  0
1      id_unidade  0
2            nome  0
3           cargo  0
4    departamento  0
5         salario  6
6   data_admissao  0

### Nulos e duplicados:

#### Nulos:

In [63]:
df.isnull().sum().reset_index()

            index  0
0  id_funcionario  0
1      id_unidade  0
2            nome  0
3           cargo  0
4    departamento  0
5         salario  6
6   data_admissao  0

In [64]:
df[df.isnull().any(axis=1)]

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
8,9,1,Bruno Costa,Auxiliar De Limpeza,Governança,NaN,2021-11-02
13,14,1,Yuri Castro,Analista Financeiro,Financeiro,NaN,2022-12-31
36,37,4,Larissa Sousa,Cozinheiro,Alimentos e Bebidas,NaN,2019-09-29
42,43,4,Wilson Duarte,Analista Financeiro,Financeiro,NaN,2022-01-07
91,92,9,Wilson Duarte,Gerente,Administração,NaN,2024-02-29
103,104,10,Vanessa Cavalcanti,Cozinheiro,Alimentos e Bebidas,NaN,2024-05-27

In [74]:
df[df.duplicated(subset=['nome','departamento', 'cargo', 'id_unidade'], keep=False)].sort_values(by='nome')

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
60,61,6,Kleber Pires,Camareira,Governança,1531.0,2022-05-26
62,63,6,Kleber Pires,Camareira,Governança,1616.0,2018-11-03

In [66]:
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar De Limpeza,Governança,2139.0,2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,Analista Financeiro,Financeiro,5356.0,2022-03-01
3,4,1,Julia Monteiro,Auxiliar De Limpeza,Governança,2070.0,2019-06-10
4,5,1,Daniela Ramos,Auxiliar De Limpeza,Governança,1572.0,2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,Segurança,Segurança,1976.0,2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    float64
 6   data_admissao   134 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 7.5 KB