In [17]:
import pandas as pd
import numpy as np

In [18]:
df_antigo = pd.read_csv('../../dados/raw/unidades.csv', sep=';')
df_novo = pd.read_csv('../../dados/raw/unidades_novos.csv', sep=';')

In [19]:
df = pd.concat(
    [df_antigo, df_novo],
    ignore_index=True
)
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3 estrelas,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,70.0
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,75.0
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5 estrelas,40.0

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_unidade         13 non-null     int64
 1   nome_unidade       13 non-null     str
 2   cidade             13 non-null     str
 3   regiao             13 non-null     str
 4   categoria_hotel    13 non-null     str
 5   num_quartos_total  13 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 756.0 bytes

### Tratamentos de texto:

#### Tratamento de região:

In [21]:
df['regiao'] = df['regiao'].str.strip().str.title()

In [22]:
map_regiao = {
    'Cap': 'Capital',
}
df['regiao'] = df['regiao'].map(map_regiao).fillna(df['regiao'])

In [23]:
df['regiao'].value_counts().reset_index()

               regiao  count
0             Capital      5
1               Serra      3
2         Costa Verde      3
3  Baixada Fluminense      2

In [24]:
df['nome_unidade'].value_counts().reset_index()

                     nome_unidade  count
0              NaraHoteis Ipanema      1
1      NaraHoteis Barra da Tijuca      1
2               NaraHoteis Centro      1
3         NaraHoteis Santa Teresa      1
4   NaraHoteis Nova Iguaçu Centro      1
5     NaraHoteis Nova Iguaçu Park      1
6           NaraHoteis Petrópolis      1
7          NaraHoteis Teresópolis      1
8             NaraHoteis Friburgo      1
9               NaraHoteis Paraty      1
10      NaraHoteis Angra dos Reis      1
11         NaraHoteis Mangaratiba      1
12  NaraHoteis Copacabana Premium      1

#### Tratando estrelas:

In [25]:
df['categoria_hotel'] = df['categoria_hotel'].str.strip().str.title()

In [26]:
df['categoria_hotel'].value_counts().reset_index()

  categoria_hotel  count
0      4 Estrelas      5
1      5 Estrelas      4
2              3*      1
3   Três Estrelas      1
4      3 Estrelas      1
5  Cinco Estrelas      1

In [27]:
map_cathotel = {
    'Cinco Estrelas': '5 Estrelas',
    'Três Estrelas': '3 Estrelas',
    '3*': '3 Estrelas',
}
df['categoria_hotel'] = df['categoria_hotel'].map(map_cathotel).fillna(df['categoria_hotel'])

In [28]:
df['categoria_hotel'].value_counts().reset_index()

  categoria_hotel  count
0      5 Estrelas      5
1      4 Estrelas      5
2      3 Estrelas      3

In [29]:
df['num_quartos_total'] = df['num_quartos_total'].astype('Int64')

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_unidade         13 non-null     int64
 1   nome_unidade       13 non-null     str
 2   cidade             13 non-null     str
 3   regiao             13 non-null     str
 4   categoria_hotel    13 non-null     str
 5   num_quartos_total  13 non-null     Int64
dtypes: Int64(1), int64(1), str(4)
memory usage: 769.0 bytes

In [31]:
df

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 Estrelas,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4 Estrelas,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3 Estrelas,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4 Estrelas,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3 Estrelas,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3 Estrelas,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 Estrelas,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 Estrelas,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 Estrelas,75
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5 Estrelas,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 Estrelas,50
12,13,NaraHoteis Copacabana Premium,Rio de Janeiro,Capital,5 Estrelas,40

In [32]:
df.to_csv('../../dados/clean/unidades.csv', sep=';', encoding='UTF-8', decimal='.', index=False)